### PR TITLE
export-metadata-upload: create content

### PR DESCRIPTION
**Pull request by matt-maguire**
created high-level summary of export process in workflow section.

### CODE REVIEW

**Comment by elstoc** [comment]
Thanks @matt-maguire. It probably needs a bit more information about adding metadata to images though, given the title.

**Comment by matt-maguire** [comment]
The mechanics of selecting which metadata to export should be covered in the export-slected lighttable module. In this section, we are more providing guidance on what high level activities should happen. Maybe I can mention something about the types of metadata that can be exported into the jpeg

**Comment by elstoc** [comment]
I was thinking more along the lines of adding metadata to images, with reference to the tagging and metadata editor modules. But yeah - very high level.

**Comment by matt-maguire** [comment]
That would more properly belong in the import, rate, tag section. At time of export, you are not normally adding metadata, you are selecting which metadata to write out.

**Comment by elstoc** [comment]
Ah yes indeed you're right.

**Pull request merged**
