### PR TITLE
color-calibration: explain more about valid slider settings on grey tab

### PR DESCRIPTION
**Pull request by matt-maguire**
In darktable-org/darktable#6854 it was explained that the sliders on the grey tab of *color-calibration* need to add up to something non-zero, so this updates the doc to clarify valid slider settings.

### CODE REVIEW

**Comment by elstoc** [comment]
That's only true if you don't choose to normalize channels though

**Comment by matt-maguire** [comment]
Really? When I tested, it seemed the monochrome treatment was disabled even when normalisation was off. It is a bit of a pathological case though, because without normalisation as the sum approaches zero the image will be quite dim.

**Comment by elstoc** [comment]
Sorry I meant that the bit you've put about the image going black with negative values isn't correct with normalisation.

**Comment by matt-maguire** [comment]
Yes, you're right, because dividing a negative with a negative gives you a positive. So, I just removed the comment about negative totals altogether, in order to not overcomplicate things.

**Comment by elstoc** [comment]
ok thanks

**Pull request merged**
