### PR TITLE
[Issue #45] clarify filmic-rgb clipping indicators

### LINKED ISSUE #45: filmic-rgb: orange clipping indicators not clearly explained
There was a discussion on pixls.us about filmic orange clipping indicators:
https://discuss.pixls.us/t/filmic-differences-in-curves-3-2-1-vs-3-3-0-dev-and-out-of-the-box-curve-in-3-3-0-dev/20713/11

This topic should be better treated in the usermanual.

### PR DESCRIPTION
**Pull request by matt-maguire**
Fixes #45 

Clarify about the orange clipping indicators on filmic S-curve and what actions can be taken to deal with them.

### CODE REVIEW

**Comment by matt-maguire** [comment]
Added also screenshots of the diagrams, and improved the description of the "look only" graph, to explain better what the parts of the curve means, and included an example of the orange spline overshoot warning as a visual aid.

**Comment by elstoc** [comment]
Looks good to me. I think we can probably do away with the screenshot at the start now. What do you think?

**Comment by matt-maguire** [comment]
redundant image removed.

**Comment by elstoc** [comment]
Thanks.

**Pull request merged**
