### PR TITLE
history-stack: document pr#6520 safe history copy

### PR DESCRIPTION
**Pull request by matt-maguire**
Documents darktable-org/darktable#6520

### CODE REVIEW

**Comment by elstoc** [comment]
Let's wait and see how this feature is received before merging this.

**Comment by junkyardsparkle** [comment]
I agree that there could be some backlash against this change, we'll see. This makes me ask: would it be within the scope of this project to maintain a prominent list of potential "gotchas" for each version to help keep people from encountering these kinds of changes as (possibly slow-to-be-noticed) "bugs"? I have a feeling people don't always read the release notes...

**Comment by matt-maguire** [comment]
If they don't read the release notes, they are unlikely to read the udser manual. That said, some sort of a "FAQ" or "Hot Tips" in the guides and tutorials section could be a useful reference for people, which could capture some of those "gotchas".

**Comment by elstoc** [comment]
I think that something like that should be stored separately, perhaps in a wiki on the main darktable project, with a link from the user manual.

**Comment by elstoc** [comment]
Guess this needs updating now. Suspect this feature isn't likely to change again before 3.4.

**Comment by matt-maguire** [comment]
Looks like the list of "safe" modules hasn't changed at all, only change seems to be the button names. Updated the history stack utility module page accordingly.

**Comment by elstoc** [comment]
Thanks

**Pull request merged**
