### PR TITLE
manage-module-layouts: document the new set of presets from PR 6489

### LINKED ISSUE #87: Document module grouping feature
@AlicVB has proposed an update the the usermanual concerning the new module grouping feature in PR darktable-org/darktable#6576

This needs to be proof-read and converted to markdown.

### PR DESCRIPTION
**Pull request by matt-maguire**
fixes #87 

redo screenshot, and describe the new set of built-in presets.

### CODE REVIEW

**Comment by elstoc** [comment]
Thanks @matt-maguire. Just a small nit-pick - could you redo the screenshot without the mouse pointer in it please.

**Comment by matt-maguire** [comment]
I only put the mouse pointer there, because you had it in your original screenshot lol

Let me push update without it.

**Comment by elstoc** [comment]
> I only put the mouse pointer there, because you had it in your original screenshot lol

Oh my bad then. There are some where it makes sense (like the spline controls one) but generally just makes me think "is that my mouse or part of the image"?

**Comment by elstoc** [comment]
Thanks.

**Pull request merged**
