### PR TITLE
Typo fixes + additional info for preserve details = 'no'

### PR DESCRIPTION
**Pull request by kofa73**
'dependant' is a noun, dependent is an adjective (and, in US English, also a noun). I don't think 'independant' exists.

For the 'preserve details' change, quoting Aurélien:
'If you don’t use the details preservation option, the tone equalizer falls back to a simple tone curve with built-in chroma preservation. That’s good if you want to increase the contrast in a picture and don’t mind the over-sharpening (aka you want local and global contrast increase).' -> https://discuss.pixls.us/t/darktable-tone-equalizer-help-wanted/14549/8 ->

### CODE REVIEW

**Comment by elstoc** [comment]
Looks good to me. Thanks @kofa73.

**Comment by matt-maguire** [comment]
See, that's what happens when I study too much French (indépendant(e)). Now I can't spell in English properly :-(

**Comment by kofa73** [comment]
> See, that's what happens when I study too much French (indépendant(e)). Now I can't spell in English properly :-(

I know your pain. I'm learning German now (living in Switzerland), and it affects my English: the other day I wanted to write the word 'albeit', and wrote 'albiet', because, you know, 'ei' is pronounced like the English 'eye', and 'ie' is the way to spell the 'ee' sound...

**Comment by matt-maguire** [comment]
I used to live in Stuttgart, not so far from Zürich, and it is a beautiful part of the world, but the German I learnt there did my head in as well :-)

Anyway, thanks very much or your contribution to the docs, both grammar and content-wise.

**Pull request merged**
